### ISSUE TITLE
Dead link for "A Non-Euclidean View [...]" by Ursula K. Le Guin

### ISSUE THREAD

**Issue by CorentinBrule** [frnsys/speculating_futures#4]
The link to [A Non-Euclidean View of California as a Cold Place to Be](http://theanarchistlibrary.org/library/ursula-k-le-guin-a-non-euclidean-view-of-california-as-a-cold-place-to-be) by Ursula K. Le Guin is break. But a spnashot from the last june is available on [Internet Archive](https://web.archive.org/web/20180628075056/http://theanarchistlibrary.org/library/ursula-k-le-guin-a-non-euclidean-view-of-california-as-a-cold-place-to-be).

**Comment by frnsys** [comment]
thanks for catching that -- it's been updated.
